routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Users\UserController;
use App\Http\Controllers\Ajax\AjaxController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [HomeController::class, 'index'])->name('home');
Route::get('/', function(){
    return view('welcome');
});
Route::get('/t', function () {
    event(new \App\Events\SendMessage());
    // dd('Event Run Successfully.');
});

Auth::routes();
Route::group(['middleware' => ['auth']], function(){
    Route::get('/home', [HomeController::class, 'index'])->name('home');

    /*User Routing*/
    Route::resource('users', UserController::class);

    /* get all states */
    Route::get('all-states', [AjaxController::class, 'getAllStates'])->name('all-states');
    Route::get('get-cities', [AjaxController::class, 'getAllCities'])->name('all-cities');

    /* check email address */
    Route::post('/check-email-address',[AjaxController::class, 'checkEmail']);

    /* Notification mail */
    Route::get('send', [HomeController::class, 'sendNotification']);
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'mobileNo',
        'city',
        'state',
        'address',
        'image',
        'designation'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasRole(String $roleName)
    {
        return $this->roles()->where('name', $roleName)->exists();
    }

    public function roles()
    {
        return $this->belongsToMany('App\Models\Role');
    }
    public function addRole(String $roleName)
    {
        $role = Role::where('name', $roleName)->first();

        if ($role) $this->roles()->save($role);
    }
}

app/Http/Controllers/Users/UserController.php
<?php

namespace App\Http\Controllers\Users;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Role;
use App\Models\RoleUser;
use App\Models\User;
use Validator;
use File;
use Illuminate\Support\Facades\Hash;
use Illuminate\Pagination\Paginator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data =  User::whereHas('roles', function($role) {
            $role->where('name','User');
        })->paginate(4);
        
        return view('pages.users.list', compact('data'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $allRoles = Role::all();
        return view('pages.users.create', compact('allRoles'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Validator::make($request->all(), [
        'name'     => 'required |string',
        'email'    => 'required |string | email | max:255 | unique:users',
        'password' => 'required|string|min:5',
        'mobileNumber' => 'required|digits:10',
        'state'    => 'required',
        'city'     => 'required',
        'address'  => 'required',
        'image'    => 'image|mimes:jpeg,png,jpg,gif|max:2048'
        ],
        [
            'name.required'       => 'First name is required.',
            'email.required'      => 'Email is required.',
            'email.email'         => 'Please enter a valid email address.',
            'password.required'   => 'Password is required.',
            'password.min'        => 'Minimum 5 character is required.',
            'mobileNumber.required'   => 'Contact number is required.',
            'mobileNumber.digits'     => 'Enter valid mobile number.',
            'state.required'      => 'State is required.',
            'city.required'       => 'City is required.',
            'address.required'    => 'Address is required.',
        ])->validate();
        
        if ($image = $request->file('image')) {
            $destinationPath = 'images/userImage';

            $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $profileImage);
            // $input['image'] = "$profileImage"; 
            $user = User::create([
                'name'        =>  $request->input('name'),
                'email'       =>  $request->input('email'),
                'password'    =>  Hash::make($request->input('password')),
                'mobileNo'    =>  $request->input('mobileNumber'),
                'designation' =>  $request->input('designation')? $request->input('designation') : 2,
                'state'       =>  $request->input('state'),
                'city'        =>  $request->input('city'),
                'address'     =>  $request->input('address'),
                'image'       => $profileImage
            ]);
            $user->save();
            $user->addRole(Role::User);
        }else{
            $user = User::create([
                'name'        =>  $request->input('name'),
                'email'       =>  $request->input('email'),
                'password'    =>  Hash::make($request->input('password')),
                'mobileNo'    =>  $request->input('mobileNumber'),
                'designation' =>  $request->input('designation')? $request->input('designation') : 2,
                'state'       =>  $request->input('state'),
                'city'        =>  $request->input('city'),
                'address'     =>  $request->input('address'),
            ]);
            $user->save();
            $user->addRole(Role::User);
        }
        if($user){
            $request->session()->flash('success', 'User added successfully .');
            return redirect()->route('users.index');
        }
        $request->session()->flash('error', 'User is not added successfully .');
        return redirect()->route('users.create');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $userData = User::findOrfail($id);
        $roles = Role::all();
        if($userData){
            return response()->json(['userData'=>$userData,'roles'=>$roles],200);
        }else{
            return response()->json(['pm_data'=>'Project manager not found.'],403);
        }
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $userData = User::findOrfail($id);
        $allRoles = Role::all();
        return view('pages.users.edit', compact('allRoles', 'userData'));
        //
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        Validator::make($request->all(), [
            'name'     => 'required |string',
            'mobileNumber' => 'required|digits:10',
            'state'    => 'required',
            'city'     => 'required',
            'address'  => 'required',
            'image'    => 'image|mimes:jpeg,png,jpg,gif|max:2048'
            ],
            [
                'name.required'       => 'First name is required.',
                'mobileNumber.required'   => 'Contact number is required.',
                'mobileNumber.digits'     => 'Enter valid mobile number.',
                'state.required'      => 'State is required.',
                'city.required'       => 'City is required.',
                'address.required'    => 'Address is required.',
            ])->validate();
            
            if ($image = $request->file('image')) {
                $userData = User::findOrfail($id);
                // $oldFilePath = asset('/images/userImage').'/'.$userData->image;
                $oldFilePath = public_path('/images/userImage/' . $userData->image);
                /* check old file and deletefile */
                if (File::exists($oldFilePath)){
                    // unlink($oldFilePath);
                    chmod($oldFilePath, 0644);
                    unlink($oldFilePath);
                    echo 'Deleted old image';
                 }
                $destinationPath = 'images/userImage';
    
                $profileImage = date('YmdHis') . "." . $image->getClientOriginalExtension();
                $image->move($destinationPath, $profileImage);
                // $input['image'] = "$profileImage"; 
                $user = User::find($id)->update([
                    'name'        =>  $request->input('name'),
                    'mobileNo'    =>  $request->input('mobileNumber'),
                    'designation' =>  $request->input('designation')? $request->input('designation') : 2,
                    'state'       =>  $request->input('state'),
                    'city'        =>  $request->input('city'),
                    'address'     =>  $request->input('address'),
                    'image'       => $profileImage
                ]);
            }else{
                $user = User::find($id)->update([
                    'name'        =>  $request->input('name'),
                    'mobileNo'    =>  $request->input('mobileNumber'),
                    'designation' =>  $request->input('designation')? $request->input('designation') : 2,
                    'state'       =>  $request->input('state'),
                    'city'        =>  $request->input('city'),
                    'address'     =>  $request->input('address'),
                ]);
            }
            if($user){
                $request->session()->flash('success', 'User Profile updated successfully .');
                return redirect()->route('users.index');
            }
            $request->session()->flash('error', 'User profile is not updated.');
            return redirect()->route('users.create');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,$id)
    {
        $userData = User::find($id)->delete();
        $RoleUser = RoleUser::where('user_id',$id)->delete($id);
        $request->session()->flash('success', 'User Profile deleted successfully');
    }
}

resources/views/pages/users/create.blade.php
@extends('layouts.app',['title'=>'Create User'])

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Add User</div>
                    <form class="form-4horizontal" id="addUser" method="post" enctype="multipart/form-data"
                        action="{{ route('users.store') }}">
                        <div class="card-body">
                            @csrf
                            @if (session()->has('success'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ Session::get('success') }}</strong>
                                </div>
                            @endif
                            @if (session()->has('error'))
                                <div class="alert alert-success alert-block">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <strong>{{ Session::get('error') }}</strong>
                                </div>
                            @endif
                            <div class="form-group">
                                <label for="name" class="cols-sm-2 control-label">Name<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                                        id="name" placeholder="Enter your Name" />
                                    @error('name')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email" class="cols-sm-2 control-label">Email Address<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">

                                    <input type="text" class="form-control @error('email') is-invalid @enderror"
                                        name="email" id="email" placeholder="Enter your Email" />
                                    @error('email')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password" class="cols-sm-2 control-label">Password<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">
                                    <input type="password" class="form-control @error('password') is-invalid @enderror"
                                        name="password" id="password" placeholder="Enter your Password" />.
                                    @error('password')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="mobileNumber" class="cols-sm-2 control-label">Mobile Number<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">
                                    <input type="text" class="form-control @error('mobileNumber') is-invalid @enderror"
                                        name="mobileNumber" id="mobileNumber" placeholder="Enter your Mobile Number" />
                                    @error('mobileNumber')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="designation" class="cols-sm-2 control-label">Designation</label>
                                <div class="cols-sm-10">
                                    <select name="designation" id="designation" class="form-control">
                                        <option value="">Select Designation</option>
                                        @forelse ($allRoles as $roleKey => $roleValue)
                                            <option value="{{ $roleValue->id }}">{{ $roleValue->name }}</option>
                                        @empty
                                        @endforelse
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="image" class="cols-sm-2 control-label">Profile Image</label>
                                <div class="cols-sm-10">

                                    <input type="file"
                                        class="form-control @error('image') is-invalid @enderror border border-0"
                                        name="image" id="image" />
                                    @error('image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="state" class="cols-sm-2 control-label">State<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">
                                    @php
                                        $state = App\Helpers\StateCityHelper::getStates();
                                    @endphp
                                    <select name="state" id="state"
                                        class=" form-control @error('state') is-invalid @enderror">
                                        <option value="">Select State</option>
                                        @foreach ($state as $stateKey => $stateValue)
                                            <option value="{{ $stateValue['state_name'] }}">
                                                {{ $stateValue['state_name'] }}</option>
                                        @endforeach
                                    </select>
                                    @error('state')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="city" class="cols-sm-2 control-label">City<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">

                                    <select name="city" id="city" class="form-control @error('city') is-invalid @enderror">
                                        <option value="">Select City</option>
                                    </select>
                                    @error('city')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="password" class="cols-sm-2 control-label">Address<span
                                        class="text-danger">*</span></label>
                                <div class="cols-sm-10">
                                    <textarea name="address" class="form-control @error('address') is-invalid @enderror"
                                        id="address"></textarea>
                                    @error('address')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group ">
                                <button type="submit" class="btn btn-primary btn-sm">{{ __('Add User') }}</button>
                                <button type="reset" class="btn btn-danger btn-sm">{{ __('Reset') }}</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection